// <auto-generated />
namespace CRM_BL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update6182019 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update6182019));
        
        string IMigrationMetadata.Id
        {
            get { return "201906171801200_update6182019"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
